on:
  workflow_dispatch:

defaults:
  run:
    shell: cmd
    
jobs:
  build_windows_debug:
    runs-on: [ self-hosted ]
    timeout-minutes: 60
    steps:
      - name: Enable long path names
        run: git config --global core.longpaths true
        
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PAT }}
          submodules: recursive
          
      - name: Create credentials file for build script
        run: |
          echo ${{ secrets.USERNAME }},${{ secrets.PASSWORD }} >> cli_credentials.csv
          
      - name: Build Project for Windows Debug
        run: |
          set PATH=C:\\openjdk-18.0.1.1_windows-x64_bin\\jdk-18.0.1.1;%PATH%
          build.bat --win_debug -nostart
